### ISSUE TITLE
(URGENT) Failure in PDF generation (mn2pdf)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#150]
Commands:
```
cd sources
bundle exec metanorma si-brochure-en.adoc
```

MN presentation XML:
[si-brochure-en.presentation.xml.zip](https://github.com/metanorma/bipm-si-brochure/files/7119004/si-brochure-en.presentation.xml.zip)

Output:
```
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mn2pdf-1.35/lib/../bin/mn2pdf.jar --xml-file "si-brochure-en.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.1.8/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "si-brochure-en.pdf" --font-manifest /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20210907-91894-10e75v9.yml
[mn2pdf] Fatal: mn2pdf 



Input: XML (si-brochure-en.presentation.xml)
Input: XSL (/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.1.8/lib/isodoc/bipm/bipm.brochure.xsl)
Output: PDF (si-brochure-en.pdf)

[INFO] XSL-FO file preparation...
[INFO] Rendering into intermediate format for index preparation... file:/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.1.8/lib/isodoc/bipm/bipm.brochure.xsl; Line #353; Column #124; java.lang.NoSuchMethodException: For extension function, could not find method static org.metanorma.fop.Util.saveFileToDisk([ExpressionContext,] #NODESET, #NODESET).
file:/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.1.8/lib/isodoc/bipm/bipm.brochure.xsl; Line #348; Column #76; java.lang.NullPointerException: Cannot invoke "org.apache.xpath.objects.XObject.allowDetachToRelease(boolean)" because "var" is null
java.awt.FontFormatException: bad pfa font
	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:321)
	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:299)
	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2258)
	at java.desktop/java.awt.Font.<init>(Font.java:615)
	at java.desktop/java.awt.Font.createFont(Font.java:1219)
	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:769)
	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:440)
	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:731)
	at org.metanorma.fop.mn2pdf.runSecondPass(mn2pdf.java:631)
	at org.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:237)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:528)
Sep 07, 2021 1:03:18 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Sep 07, 2021 1:03:18 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
[FATAL] "fo:root" is missing child elements. Required content model: (layout-master-set, declarations?, bookmark-tree?, (page-sequence|fox:external-document)+) (See position 1:446)
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:root" is missing child elements. Required content model: (layout-master-set, declarations?, bookmark-tree?, (page-sequence|fox:external-document)+) (See position 1:446)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at org.metanorma.fop.mn2pdf.runSecondPass(mn2pdf.java:667)
	at org.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:237)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:528)
Caused by: org.apache.fop.fo.ValidationException: "fo:root" is missing child elements. Required content model: (layout-master-set, declarations?, bookmark-tree?, (page-sequence|fox:external-document)+) (See position 1:446)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy9.missingChildElement(Unknown Source)
	at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
	at org.apache.fop.fo.pagination.Root.endOfNode(Root.java:117)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1727)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2898)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	... 3 more
---------
org.apache.fop.fo.ValidationException: "fo:root" is missing child elements. Required content model: (layout-master-set, declarations?, bookmark-tree?, (page-sequence|fox:external-document)+) (See position 1:446)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy9.missingChildElement(Unknown Source)
	at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
	at org.apache.fop.fo.pagination.Root.endOfNode(Root.java:117)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1727)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2898)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.mn2pdf.runSecondPass(mn2pdf.java:667)
	at org.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:237)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:528)
```

**Comment by Intelligent2013** [comment]
Latest BIPM xslt (with hidden text feature) works only with mn2pdf v1.36 (https://github.com/metanorma/mn2pdf/releases/tag/v1.36), but in your command line version 1.35 is using:
`/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mn2pdf-1.35/lib/../bin/mn2pdf.jar`

Unfortunately, mn2pdf-ruby v1.36 didn't released due the error:
(https://github.com/metanorma/mn2pdf-ruby/runs/3444650571?check_suite_focus=true)

```
Run bundle exec rake
  bundle exec rake
  shell: /bin/bash -e {0}
  env:
    MN2PDF_VERSION: 1.36
/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/ruby -I/opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib:/opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/rspec-support-3.10.2/lib /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Mn2pdf
  gem version more or equal to JAR version
  help not empty (FAILED - 1)
java -Xss5m -Xmx2048m -jar /home/runner/work/mn2pdf-ruby/mn2pdf-ruby/lib/../bin/mn2pdf.jar --xml-file /home/runner/work/mn2pdf-ruby/mn2pdf-ruby/spec/fixtures/G.191.xml --xsl-file /home/runner/work/mn2pdf-ruby/mn2pdf-ruby/spec/fixtures/itu.recommendation.xsl --pdf-file /tmp/d20210827-2242-1d8606r/G.191.pdf 
  converts XML to PDF
java -Xss5m -Xmx2048m -jar /home/runner/work/mn2pdf-ruby/mn2pdf-ruby/lib/../bin/mn2pdf.jar --xml-file missing.xml --xsl-file /home/runner/work/mn2pdf-ruby/mn2pdf-ruby/spec/fixtures/itu.recommendation.xsl --pdf-file missing.pdf 
  raise an error on converting not existing XML

Failures:

  1) Mn2pdf help not empty
     Failure/Error: expect(Mn2pdf.help).not_to be_empty
       expected `"".empty?` to be falsey, got true
     # ./spec/mn2pdf_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 18.39 seconds (files took 0.14074 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/mn2pdf_spec.rb:9 # Mn2pdf help not empty

/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/ruby -I/opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib:/opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/rspec-support-3.10.2/lib /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I can't figure out what does mean:
```

  1) Mn2pdf help not empty
     Failure/Error: expect(Mn2pdf.help).not_to be_empty
       expected `"".empty?` to be falsey, got true
     # ./spec/mn2pdf_spec.rb:10:in `block (2 levels) in <top (required)>'
```

**Comment by Intelligent2013** [comment]
I've checked this for 1.35 gem (previous successfully released gem)
```
require 'mn2pdf'
Mn2pdf.help()
```
and it doesn't return anything...

**Comment by Intelligent2013** [comment]
The reason was in the changing from:
```
System.out.println(USAGE);
```
to:
```
logger.info(USAGE);
```

logger outputs all messages into System.err (https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.5): `ConsoleHandler: A simple handler for writing formatted records to System.err`

Fixed in mn2pdf-ruby: https://github.com/metanorma/mn2pdf-ruby/commit/4827911bbcb8d9cf709a9ff168258ee775170e3d
