### ISSUE TITLE
Encoding the unit `"unitsml(kg*m^(p)*s^(q))"` causes parsing error in asciimath2unitsml

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#174]
This works:
```adoc
stem:["unitsml(kg*m*s^(-2)*A^(-2))"]
```

But this crashes:
```adoc
stem:["unitsml(kg*m^(p)*s^(q))"]
```

The only differences is that the powers are replaced with p and q as variables.

<img width="667" alt="Screenshot 2022-06-21 at 5 18 15 PM" src="https://user-images.githubusercontent.com/11865/174751658-e8461e94-adb3-448e-a664-f88014b8f464.png">

Trace:
```
Fatal Error: 
in source:1 at 3
kg*m^(p)*s^(q)
   ^
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/3.1.1/bin/metanorma)
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rsec-1.0.0/lib/rsec/parser.rb:19:in `parse!':  (Rsec::SyntaxError)
in source:1 at 3
kg*m^(p)*s^(q)
   ^
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/asciimath2unitsml-0.4.3/lib/asciimath2unitsml/parse.rb:56:in `parse_units'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/asciimath2unitsml-0.4.3/lib/asciimath2unitsml/parse.rb:51:in `parse'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/asciimath2unitsml-0.4.3/lib/asciimath2unitsml/parse.rb:129:in `block in MathML2UnitsML'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/asciimath2unitsml-0.4.3/lib/asciimath2unitsml/parse.rb:124:in `MathML2UnitsML'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-5493fa9a68b6/lib/metanorma/standoc/cleanup_maths.rb:215:in `block in mathml_cleanup'
```

**Comment by opoudjis** [comment]
Work on this in Plurimath

**Comment by opoudjis** [comment]
@ronaldtse agrees that this should crash, he is objecting to the error message. The syntax has been changed in bipm brochure, so this issue goes away in favour of https://github.com/plurimath/asciimath2unitsml/issues/32
