### ISSUE TITLE
(CRITICAL) Failure to generate SI Brochure collection

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#180]
This is a critical error in what it seems to be in Relaton, where the edition is expected to be an object but the data is an integer.

It is possible that this error stems from the fact that Metanorma is generating the metadata of the language-specific SI Brochure with edition as a number.

This is blocking the publication of the SI Brochure.

```sh
$ bundle exec metanorma collection collection.yml -x xml,html,presentation,pdf -w bilingual-brochure -c sources/collection_cover.htm
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[relaton-bib] document type "collection" is invalid.





Render Init: 13:42:40
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/3.1.1/bin/metanorma)
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-bib-1.12.1/lib/relaton_bib/bibliographic_item.rb:748:in `block in render_xml': undefined method `to_xml' for 9:Integer (NoMethodError)

        edition&.to_xml builder
               ^^^^^^^^
Did you mean?  to_yaml
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-bib-1.12.1/lib/relaton_bib/bibliographic_item.rb:734:in `render_xml'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-bib-1.12.1/lib/relaton_bib/bibliographic_item.rb:340:in `block in to_xml'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-bib-1.12.1/lib/relaton_bib/bibliographic_item.rb:339:in `new'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-bib-1.12.1/lib/relaton_bib/bibliographic_item.rb:339:in `to_xml'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.12.1/lib/relaton_bipm/bipm_bibliographic_item.rb:58:in `to_xml'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/collection.rb:68:in `collection_body'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/collection.rb:61:in `block (2 levels) in to_xml'
```

**Comment by opoudjis** [comment]
I fixed this latest release.
