### ISSUE TITLE
Site generate for collection should not generate component PDFs twice

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#209]
The `si-brochure-en.pdf` and `si-brochure-fr.pdf` files are compiled twice when using `metanorma site generate`, once under `site/documents` and once under `site/brochure`.

This needs to be fixed. (cc @abunashir)

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/186#issuecomment-1305199238_

**Comment by ronaldtse** [comment]
Here's the full log. You can clearly see the duplicated commands:

```
[info]: Compiling /Users/me/src/mn/bipm-si-brochure/sources/si-brochure-en.adoc ...
...
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-en.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-en.pdf" --param baseassetpath="/Users/me/src/mn/bipm-si-brochure/sources" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-33x4gf.yml"
...

[info]: Compiling /Users/me/src/mn/bipm-si-brochure/sources/si-brochure-fr.adoc ...
...
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-fr.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-fr.pdf" --param baseassetpath="/Users/me/src/mn/bipm-si-brochure/sources" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-zzzr08.yml"
[info]: Building collection file: /Users/me/src/mn/bipm-si-brochure/site/documents.xml ...
[info]: Generating html site in /Users/me/src/mn/bipm-si-brochure/site ...
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
...

Render Init: 15:35:05
...
Render Files: 15:35:07
...
Internal Refs: 15:35:07
...

Process si-brochure-fr.html: 15:35:07
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-fr.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-fr.pdf" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-sitrum.yml"
...

Process si-brochure-en.html: 15:35:58
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-en.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-en.pdf" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-lm3p5x.yml"
...

Concatenate: 15:36:49
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/collection.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/collection.pdf" --syntax-highlight  --split-by-language  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-baqyuv.yml"
...

Coverpage: 15:39:15
...

Done: 15:39:15
Site has been generated at /Users/me/src/mn/bipm-si-brochure/site
```

## Duplicated commands: English

```
[info]: Compiling /Users/me/src/mn/bipm-si-brochure/sources/si-brochure-en.adoc ...
...
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-en.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-en.pdf" --param baseassetpath="/Users/me/src/mn/bipm-si-brochure/sources" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-33x4gf.yml"
...
Process si-brochure-en.html: 15:35:58
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-en.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-en.pdf" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-lm3p5x.yml"
```

## Duplicated commands: French

```
[info]: Compiling /Users/me/src/mn/bipm-si-brochure/sources/si-brochure-fr.adoc ...
...
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-fr.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/documents/si-brochure-fr.pdf" --param baseassetpath="/Users/me/src/mn/bipm-si-brochure/sources" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-zzzr08.yml"
...
Process si-brochure-fr.html: 15:35:07
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-fr.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-bipm-7a70de29bfeb/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "/Users/me/src/mn/bipm-si-brochure/site/brochure/si-brochure-fr.pdf" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20221107-22882-sitrum.yml"
```

**Comment by abunashir** [comment]
Hi @ronaldtse, I was trying to look into it but I'm not sure if I understand it correctly. So, we are basically explicitly specifying the files once in [metanorma.yml](https://github.com/metanorma/bipm-si-brochure/blob/main/metanorma.yml#L59), where the file is specifying that the compiler should output `pdf` along with others.

And we are also specifying to generate `pdf` files in [collection.yml](https://github.com/metanorma/bipm-si-brochure/blob/main/collection.yml#L34) file reference files, which is triggering the second pdf file generation for dependent files [from here](https://github.com/metanorma/metanorma/blob/57f0d9bcc32fd37ed5b3ea0647309422805b641d/lib/metanorma/collection_fileprocess.rb#L208)

What's the expected behaviour here? do we need to adjust the output extension we are expecting in each of those file, or generate one over another?

**Comment by abunashir** [comment]
@ronaldtse - When you have sometime could you please have a look on the last comment ⬆️

**Comment by opoudjis** [comment]
The metanorma.yml config explicitly asks for the Brochure to be compiled as a document:

````
    - sources/si-brochure/3.01/si-brochure-en.adoc
    - sources/si-brochure/3.01/si-brochure-fr.adoc
    - sources/si-brochure/3.01/collection.yml
````

So it is the compilation of the individual document PDFs in the collection that needs to be suppressed: only the concatenated PDF is needed.

````
format:
  - xml
  - html
  - presentation
  - pdf

manifest:
  level: brochure
  title: BIPM SI Brochure

  docref:
    - file: si-brochure-fr.adoc
      identifier: si-brochure-fr

    - file: si-brochure-en.adoc
      identifier: si-brochure-en
````

We do need the individual documents to be generated, in order to generate the concatenation. I'll see if we suppress an output format for an individual file, overriding the format: of the overall collection.

**Comment by opoudjis** [comment]
I don't think the solution to this is to specify formats for individual files: that's prolix and pointless, and the default should be NOT to generate individual PDFs and DOCs if there is an overall, concatenated PDF and DOC. Rather, there should be a directive individual_pdf and individual_doc, which will generate PDF or DOC for individual documents, as well as the overall PDF and DOC. And if those directives are not set, PDF and DOC should not be generated for the individual documents. (I'm not touching HTML: by their nature as a collection of files, they do need to be generated for each individual document.)

**Comment by opoudjis** [comment]
Will write test tomorrow

**Comment by opoudjis** [comment]
> I don't think the solution to this is to specify formats for individual files: that's prolix and pointless, and the default should be NOT to generate individual PDFs and DOCs if there is an overall, concatenated PDF and DOC. Rather, there should be a directive individual_pdf and individual_doc, which will generate PDF or DOC for individual documents, as well as the overall PDF and DOC. And if those directives are not set, PDF and DOC should not be generated for the individual documents. (I'm not touching HTML: by their nature as a collection of files, they do need to be generated for each individual document.)

@ronaldtse wants to be able to specify formats per collection level, which does end up as specifying formats for individual files (and manifest levels). The solution with directives works, and now I have to undo it.

**Comment by opoudjis** [comment]
sources/si-brochure/3.01/collection.yml:

````
format:
  - xml
  - html
  - presentation
  - pdf

manifest:
  level: brochure
  title: BIPM SI Brochure

  docref:
    - file: si-brochure-fr.adoc
      identifier: si-brochure-fr
      format:
        - xml
        - presentation
        - html

    - file: si-brochure-en.adoc
      identifier: si-brochure-en
      format:
        - xml
        - presentation
        - html
````

Individual documents are now no longer compiling to PDF:

````
bundle exec metanorma collection --agree-to-terms sources/si-brochure/3.01/collection.yml
/Users/nickn/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/fontist-1.21.2/lib/fontist/helpers.rb:1: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
/Users/nickn/Documents/Arbeit/upwork/ribose/bipm-si-brochure/sources/si-brochure/3.01
si-brochure-fr.adoc
/Users/nickn/Documents/Arbeit/upwork/ribose/bipm-si-brochure/sources/si-brochure/3.01
si-brochure-en.adoc
/Users/nickn/Documents/Arbeit/upwork/ribose/bipm-si-brochure/sources/si-brochure/3.01
./si-brochure-fr.xml
/Users/nickn/Documents/Arbeit/upwork/ribose/bipm-si-brochure/sources/si-brochure/3.01
./si-brochure-en.xml
[DEPRECATION] Template.register_tag is deprecated. Use Environment#register_tag instead. Called from /Users/nickn/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/metanorma-plugin-glossarist-0.2.3/lib/metanorma/plugin/glossarist/dataset_preprocessor.rb:15:in '<top (required)>'
[DEPRECATION] Template.register_filter is deprecated. Use Environment#register_filter instead. Called from /Users/nickn/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/metanorma-plugin-glossarist-0.2.3/lib/metanorma/plugin/glossarist/dataset_preprocessor.rb:17:in '<top (required)>'
[Lutaml::Model] WARN: `schemaLocation` is handled by default. No need to explecitly define at `dictionary.rb:30`





Render Init: 11:58:06





Render Files: 11:58:09





Internal Refs: 11:58:09





Process si-brochure-fr.html: 11:58:09





Process si-brochure-en.html: 11:58:32





Concatenate: 11:58:53
xml
html
presentation
pdf
presentation
java -Xss10m -Xmx3g -Djava.awt.headless=true -Dapple.awt.UIElement=true -Duser.home=/Users/nickn -jar /Users/nickn/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/mn2pdf-2.17/bin/mn2pdf.jar --xml-file "/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/collection20250328-89090-71my72.xml" --xsl-file "/Users/nickn/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/metanorma-bipm-2.6.2/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "brochure/collection.pdf" --param baseassetpath="/Users/nickn/Documents/Arbeit/upwork/ribose/bipm-si-brochure/brochure" --syntax-highlight  --split-by-language  --font-manifest "/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/fontist_locations20250328-89090-eveywx.yml"





Coverpage: 11:59:42





Done: 11:59:42

Files to delete:
vi sources/si-brochure/3.01/collection.yml
````
