### ISSUE TITLE
Site generate fails

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-si-brochure#220]
```sh
$ bundle exec metanorma site generate --agree-to-terms
[info]: Compiling /Users/andrej/RubyProjects/bipm-si-brochure/sources/sib-a4-en.adoc ...
[relaton] WARNING: cache /Users/andrej/RubyProjects/bipm-si-brochure/relaton/cache/bipm/: version is obsolete and cache is cleared.
Fatal Error: undefined method `svgmap_rewrite' for Metanorma::Utils:Module
/Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-standoc-2.7.5/lib/metanorma/standoc/cleanup_image.rb:8:in `svgmap_cleanup': undefined method `svgmap_rewrite' for Metanorma::Utils:Module (NoMethodError)
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-standoc-2.7.5/lib/metanorma/standoc/cleanup.rb:75:in `cleanup'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-generic-2.5.5/lib/metanorma/generic/converter.rb:177:in `cleanup'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-standoc-2.7.5/lib/metanorma/standoc/base.rb:209:in `makexml'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-standoc-2.7.5/lib/metanorma/standoc/base.rb:154:in `document1'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-standoc-2.7.5/lib/metanorma/standoc/base.rb:143:in `document'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-generic-2.5.5/lib/metanorma/generic/converter.rb:79:in `document'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-bipm-2.3.7/lib/metanorma/bipm/converter.rb:140:in `document'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-standoc-2.7.5/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:956:in `convert'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/convert.rb:120:in `convert'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-1.6.9/lib/metanorma/input/asciidoc.rb:17:in `process'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-1.6.9/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-1.6.9/lib/metanorma/compile.rb:59:in `process_input_adoc'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-1.6.9/lib/metanorma/compile.rb:41:in `process_input'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-1.6.9/lib/metanorma/compile.rb:33:in `compile'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/site_generator.rb:91:in `compile'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/site_generator.rb:31:in `block in generate'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/site_generator.rb:31:in `each'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/site_generator.rb:31:in `generate'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/lib/metanorma/cli.rb:34:in `start'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/exe/metanorma:25:in `block in <top (required)>'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/metanorma-cli-1.8.11/exe/metanorma:43:in `<top (required)>'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/metanorma:25:in `load'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/metanorma:25:in `<main>'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by opoudjis** [comment]
I cannot replicate, and this would have happened at the time svgmap in metanorma-utils was being refactored, so it won't be an issue any more.
