### ISSUE TITLE
Problem with Relaton-BIPM

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#49]
I'm getting this error with this:

```
bundle exec metanorma sources/mep-kelvin-definition-en.adoc
```

Error:
```
[relaton-bipm] ("BIPM SI Brochure") fetching...
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/metanorma)
URI::InvalidURIError: bad URI(is not URI?): "https://raw.githubusercontent.com/relaton/relaton-data-bipm/master/data/si brochure.yaml"
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67:in `split'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/common.rb:737:in `URI'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bipm-1.5.0/lib/relaton_bipm/bipm_bibliography.rb:14:in `search'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bipm-1.5.0/lib/relaton_bipm/bipm_bibliography.rb:39:in `get'
```

These seem to work:
```
[relaton-bipm] ("BIPM si-brochure") fetching...
[relaton-bipm] ("BIPM si-brochure") found si-brochure
```

I believe this is due to the keywords in "BIPM {...}". Maybe Relaton BIPM needs to be more robust.

Ping @andrew2net for help. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse it's due to break space in `SI Brochure`. We can change the code to replace the space with a dash.

**Comment by andrew2net** [comment]
This issue is fixed in relaton-bipm v 1.6.1

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by ronaldtse** [comment]
@andrew2net can you also ensure that Relaton doesn't crash when the input cannot be found ? It should always fail gracefully (e.g. "NotFound error").

**Comment by andrew2net** [comment]
@ronaldtse this gem has a `NotFoud` error handling but this issue doesn't relate to the error. This issue happened because of break-spaces in a reference. Now all break-spaces are replaced by dashes.
